server:
  port: 8005

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: create-service
        uri: lb://create-service
        predicates:
          - Path=/creation/**
