content:
  name: content-create
  version: 0.0.3
  description: 测试环境

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.102.133.252:3306/content_creation?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8
    username: root
    password: xmyabc
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开 PSCache，并且指定每个连接上 PSCache 的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的 filters，去掉后监控界面 SQL 无法统计，'wall' 用于防火墙
    filters: stat,wall,slf4j

  #邮件服务
  mail:
    # 邮件服务地址
    host: smtp.qq.com
    # 端口,可不写默认
    # 编码格式
    default-encoding: utf-8
    # 用户名
    username: 1743185983@qq.com
    # 授权码，准备工作获取的代码
    password: hvqmdxwgcmhccedi
    # 其它参数
    properties:
      mail:
        smtp:
           # 如果是用 SSL 方式，需要配置如下属性,使用qq邮箱的话需要开启
          ssl:
            enable: true
            required: true
          # 邮件接收时间的限制，单位毫秒
          timeout: 10000
          # 连接时间的限制，单位毫秒
          connectiontimeout: 10000
          # 邮件发送时间的限制，单位毫秒
          writetimeout: 10000

  #Nacos 服务地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

aliyun:
  regionId: cn-shanghai
  accessKeyId: 
  secret: 
  labelList:
    - spam
    - politics
    - abuse
    - terrorism
    - porn
    - flood
    - contraband
  sceneList:
    - porn
    - terrorism
