content:
  name: content-create
  version: 0.0.3
  description: 测试环境

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.102.133.252:3306/content_creation?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8
    username: root
    password: xmyabc
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开 PSCache，并且指定每个连接上 PSCache 的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的 filters，去掉后监控界面 SQL 无法统计，'wall' 用于防火墙
    filters: stat,wall,slf4j

  #Nacos 服务地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

aliyun:
  regionId: cn-shanghai
  accessKeyId: LTAI4GC7apLpn2BNBCX39wR3
  secret: 2mENYLYnCgkB7CzRiuWZR45K6njsPA
  labelList:
    - spam
    - politics
    - abuse
    - terrorism
    - porn
    - flood
    - contraband
  sceneList:
    - porn
    - terrorism