server:
  port: 8001

# 自定义配置
content:
  name: content-create
  version: 0.0.1
  description: 创作分享

spring:
  application:
    name: create-service
  profiles:
    active: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.create.pojo.domain  #实体类路由映射
  type-enums-package: com.create.common.enums #开启枚举字段映射
  mapper-locations: mapper/**/*Mapper.xml
  # mybatis 日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl